export const SideBarOptions = [
    { id: 1, name: "Radio", href: "/radio", image: "/butradio.gif" },
    { id: 2, name: "Records", href: "/record", image: "/butrecs.jpg" },
    { id: 3, name: "Resources", href: "/resources", image: "/butwork.jpg" },
    { id: 4, name: "About", href: "/about", image: "/butbiog.jpg" },
    { id: 5, name: "Photos", href: "/photos", image: "/butpix.jpg" },
    { id: 6, name: "Albums", href: "/albums", image: "/butdiscg.jpg" },
    { id: 7, name: "Contact", href: "/contact", image: "/butcont.jpg" },
    { id: 8, name: "LGBT+", href: "/LGBT+", image: "/butspla.gif" },
    { id: 9, name: "Gigs", href: "/gigs", image: "/mast.jpg" },
    { id: 10, name: "Video", href: "/video", image: "/butvids.jpg" },
    { id: 11, name: "Action", href: "/action", image: "/butlinks.jpg" },
    { id: 12, name: "History", href: "/history", image: "/mast.jpg" },
    { id: 13, name: "Downloads", href: "/downloads", image: "/mast.jpg" },
]