export const SideBarOptions = [
    { id: 0, name: "Main Index", href: "/", image: "/mast.jpg", blurb: "Tom Robinson (b.1950) is a songwriter & broadcaster based in London, UK. Known in the 1970s as an anti-racist and LGBT campaigner he released 20 albums with various bands between 1975 and 2015. Since 2002 he's been a full-time presenter at BBC Radio 6 Music." },
    { id: 1, name: "Radio", href: "/radio", image: "/butradio.gif", blurb: "BBC Radio" },
    { id: 2, name: "Records", href: "/record", image: "/butrecs.jpg", blurb: "Albums, lyrics, songs, cover versions, translations, downloads etc" },
    { id: 3, name: "Resources", href: "/resources", image: "/butwork.jpg", blurb: "Resources For Songwriters" },
    { id: 4, name: "About", href: "/about", image: "/butbiog.jpg", blurb: "A Brief History Of Tom" },
    { id: 5, name: "Photos", href: "/photos", image: "/butpix.jpg", blurb: "Assorted pix 1973-present in no particular order Click images to enlarge" },
    { id: 6, name: "Albums", href: "/albums", image: "/butdiscg.jpg", blurb: "Detailed list of releases on vinyl, cassette and CD worldwide, supplied by fans and friends. It's far from complete - do please send us any corrections or extra info. For a simpler, broader overview see list of main albums" },
    { id: 7, name: "Contact", href: "/contact", image: "/butcont.jpg", blurb: "Use this page to receive - or stop receiving Tom's email newsletters. We will never pass on your address to a third party" },
    { id: 8, name: "LGBT+", href: "/LGBT+", image: "/butspla.gif", blurb: "CLICK HERE for BISEXUALITY PAGES at bothways.com" },
    { id: 9, name: "Gigs", href: "/gigs", image: "/mast.jpg", blurb: "Placeholder" },
    { id: 10, name: "Video", href: "/video", image: "/butvids.jpg", blurb: "Promo & live video clips for TRB and Tom Robinson" },
    { id: 11, name: "Action", href: "/action", image: "/butlinks.jpg", blurb: "Placeholder" },
    { id: 12, name: "History", href: "/history", image: "/mast.jpg", blurb: "Placeholder" },
    { id: 13, name: "Downloads", href: "/downloads", image: "/mast.jpg", blurb: "Placeholder" },
]