interface gigsType {
  date: string;
  city: string;
  venue: string;
  link: string;
  showType: string;
  sale: string;
  extraDetails: string;
}

export const upcomingGigs: gigsType[] = [
  {
    date: "11 Jun",
    city: "Sutton",
    venue: "The Sound Lounge",
    link: "https://vivenu.com/event/tom-robinson-solo-swsiam",
    showType: "Solo",
    sale: "sold out",
    extraDetails: "Solo accoustic show",
  },
  {
    date: "12 Jun",
    city: "Stowmarket",
    venue: "John Peel Centre",
    link: "https://johnpeelcentre.com/JohnPeelCentre.dll/Booking?Booking=TSelectItems.waSelectItemsPrompt.TcsWebMenuItem_0.TcsWebTab_0.TcsPerformance_507582",
    showType: "Solo",
    sale: "",
    extraDetails: "Co-headline with TV Smith celebrating 50 Years Of Punk",
  },
  {
    date: "13 Jun",
    city: "Newcastle-under-Lyme",
    venue: "The Rigger",
    link: "https://www.gigantic.com/tom-robinson-tickets/newcastle-under-lyme-the-rigger/2026-06-13-20-00",
    showType: "Solo",
    sale: "",
    extraDetails: "Solo accoustic show",
  },
  {
    date: "14 Jun",
    city: "Stanley (Co Durham)",
    venue: "White Room Music Café",
    link: "https://www.ticketsource.com/whats-on/stanley/the-white-room-music-cafe/tom-robinson-an-evening-with-at-the-white-room-music-cafe/e-emqeze",
    showType: "Solo acoustic show",
    sale: "sold out",
    extraDetails: "Solo accoustic show",
  },
  {
    date: "04 Aug",
    city: "Blackpool",
    venue: "Rebellion Run-Up at VIVA (daytime)",
    link: "https://tickets.rebellionfestivals.com/events/rebellionfestivals/2043824",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "05 Aug",
    city: "Coatbridge",
    venue: "Georgian Hotel",
    link: "https://wegottickets.com/f/16910",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "06 Aug",
    city: "Edinburgh",
    venue: "Voodoo Rooms",
    link: "https://www.seetickets.com/event/tom-robinson-with-adam-phillips/the-voodoo-rooms/3616971",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "07 Aug",
    city: "Stockton",
    venue: "ARC Arts Centre",
    link: "",
    showType: "Acoustic duo show",
    sale: "not on sale yet",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "08 Aug",
    city: "Hull",
    venue: "Wrecking Ball Arts Centre",
    link: "https://wreckingballstore.co.uk/event/tom-robinson-with-adam-phillips-then-now/",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "23 Aug",
    city: "Henley-on-Thames",
    venue: "Rewind Festival",
    link: "https://www.ticketmaster.co.uk/rewind-festival-tickets/artist/5319834",
    showType: "Festival set",
    sale: "",
    extraDetails:
      "Short set with house band. Featuring The Proclaimers, The Beat, Undertones, Nik Kershaw, Dodgy, Toyah & more",
  },
  {
    date: "24 Sep",
    city: "Manchester",
    venue: "Hallé at St Michael's",
    link: "https://www.eventim.co.uk/event/tom-robinson-with-adam-phillips-halle-at-st-michaels-21402040/",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "25 Sep",
    city: "Colchester",
    venue: "Arts Centre",
    link: "https://colchesterartscentre.ticketsolve.com/ticketbooth/shows/1173665568",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "27 Sep",
    city: "Dublin",
    venue: "Whelan's",
    link: "",
    showType: "Acoustic duo show",
    sale: "Not yet on sale",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "30 Sep",
    city: "Bangor (Co. Down)",
    venue: "The Court House",
    link: "https://courthousebangor.com/event/tom-robinson-with-adam-phillips/",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "02 Oct",
    city: "Cardiff",
    venue: "Acapela Studio",
    link: "https://acapela.co.uk/events/tom-robinson-with-adam-phillips-then-now-celebrating-50-years-of-grass-roots-music-1975-2025/",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "03 Oct",
    city: "Havant",
    venue: "Pallant Centre",
    link: "https://wegottickets.com/f/17013",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "04 Oct",
    city: "Bath",
    venue: "Komedia",
    link: "",
    showType: "Acoustic duo show",
    sale: "Not yet on sale",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "22 Oct",
    city: "London",
    venue: "Pizza Express Live (High Holborn)",
    link: "https://www.pizzaexpresslive.com/whats-on/tom-robinson-with-adam-phillips-then-and-now",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "23 Oct",
    city: "London",
    venue: "Pizza Express Live (High Holborn)",
    link: "https://www.pizzaexpresslive.com/whats-on/tom-robinson-with-adam-phillips-then-and-now",
    showType: "Acoustic duo show",
    sale: "sold out",
    extraDetails: "swith Adam Phillips",
  },
  {
    date: "24 Oct",
    city: "Birmingham",
    venue: "Midlands Arts Centre",
    link: "https://www.kitchengardencafe.co.uk/event/tom-robinson-with-adam-phillips-then-now/",
    showType: "Acoustic duo show",
    sale: "",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "25 Oct",
    city: "Shoreham",
    venue: "Ropetackle Arts Centre",
    link: "",
    showType: "Acoustic duo show",
    sale: "Not yet on sale",
    extraDetails: "with Adam Phillips",
  },
  {
    date: "22 Nov",
    city: "Camden (London)",
    venue: "Electric Ballroom(support)",
    link: "https://thegigcartel.seetickets.com/event/the-undertones-50th-anniversary-show/electric-ballroom/3564330",
    showType: "Solo acoustic show",
    sale: "",
    extraDetails: "Solo support set for The Undertones 50th Anniversary show",
  },
];
