import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Layout/Header"
import SideBar from "@/Components/Layout/SideBar"
import { NavPreviewProvider } from "@/context/NavPreviewContext"
import Blurb from "@/Components/Layout/Blurb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased h-screen overflow-hidden bg-indigo-400">

        <NavPreviewProvider>

          <div className="h-full flex justify-center bg-indigo-400">

            <div className="flex h-full flex-col w-full max-w-6xl p-2">

              <Header />

              {/* Sidebar + Main row */}
              <div className="flex flex-1 overflow-hidden">

                <SideBar />
                <div className="my-2 md:m-2 mr-0 w-full">
                  <Blurb/>
                  <main className="flex-1 overflow-y-auto">
                    {children}
                  </main>
                </div>

              </div>

            </div>

          </div>

        </NavPreviewProvider>

      </body>
    </html>
  )
}
