import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Layout/Header"
import SideBar from "@/Components/Layout/SideBar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased h-screen overflow-hidden">

        {/* Main column */}
        <div className="flex flex-col flex-1 bg-indigo-400 p-2 px-4">

          <Header />
          <SideBar />

          <main className="flex-1 overflow-y-auto">
            {children}
          </main>

        </div>


      </body>
    </html>
  );
}
