import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Layout/Header"
import SideBar from "@/Components/Layout/SideBar"
import { NavPreviewProvider } from "@/context/NavPreviewContext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased h-screen overflow-hidden bg-indigo-400">

        <NavPreviewProvider>

          <div className="h-full flex justify-center bg-indigo-400">

            <div className="flex flex-col w-full max-w-6xl p-2">

              <Header />
              <SideBar />

              <main className="flex-1 overflow-y-auto">
                {children}
              </main>

            </div>

          </div>

        </NavPreviewProvider>

      </body>
    </html>
  )
}
